-- Notificaciones generales de nuevas oportunidades de Empleo.
-- Migración aditiva e idempotente. No modifica el subsistema de seguimiento.

CREATE TABLE IF NOT EXISTS empleo_eventos_notificacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_id BIGINT NOT NULL,
    tipo TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_empleo_eventos_notificacion_tipo
        CHECK (tipo IN ('NUEVA_OPORTUNIDAD')),
    CONSTRAINT uq_empleo_eventos_notificacion_proceso_tipo
        UNIQUE (proceso_id, tipo),
    CONSTRAINT fk_empleo_eventos_notificacion_proceso
        FOREIGN KEY (proceso_id) REFERENCES procesos(id)
);

CREATE TABLE IF NOT EXISTS empleo_envios_notificacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    email TEXT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'PENDIENTE',
    proveedor_message_id TEXT,
    enviado_at TIMESTAMPTZ,
    error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_empleo_envios_notificacion_estado
        CHECK (estado IN ('PENDIENTE', 'ENVIADA', 'ERROR')),
    CONSTRAINT uq_empleo_envios_notificacion_evento_user
        UNIQUE (evento_id, user_id),
    CONSTRAINT fk_empleo_envios_notificacion_evento
        FOREIGN KEY (evento_id) REFERENCES empleo_eventos_notificacion(id)
);

CREATE INDEX IF NOT EXISTS idx_empleo_eventos_notificacion_proceso
    ON empleo_eventos_notificacion(proceso_id);

CREATE INDEX IF NOT EXISTS idx_empleo_envios_notificacion_pendientes
    ON empleo_envios_notificacion(estado, created_at);
