-- NetReto Empleo
-- Base de datos PostgreSQL independiente de la BD actual de NetReto.

CREATE TABLE organismos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    tipo TEXT NOT NULL,
    provincia TEXT,
    municipio TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE fuentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organismo_id BIGINT,
    nombre TEXT NOT NULL,
    tipo TEXT NOT NULL,
    url TEXT NOT NULL,
    prioridad INTEGER NOT NULL DEFAULT 100,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (organismo_id) REFERENCES organismos(id)
);

CREATE TABLE procesos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organismo_id BIGINT NOT NULL,
    codigo_externo TEXT,
    identificador_estable TEXT NOT NULL UNIQUE,
    denominacion TEXT NOT NULL,
    cuerpo_escala TEXT,
    grupo TEXT,
    subgrupo TEXT,
    tipo_proceso TEXT,
    sistema_selectivo TEXT,
    turno TEXT,
    plazas INTEGER,
    estado TEXT NOT NULL DEFAULT 'EN_SEGUIMIENTO',
    es_oportunidad BOOLEAN NOT NULL DEFAULT TRUE,
    anio_oep INTEGER,
    anio_convocatoria INTEGER,
    fecha_convocatoria DATE,
    fecha_apertura DATE,
    fecha_cierre DATE,
    fecha_examen TIMESTAMPTZ,
    lugar_examen TEXT,
    ultima_publicacion_at TIMESTAMPTZ,
    fuente_principal_id BIGINT,
    datos_json JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (organismo_id) REFERENCES organismos(id),
    FOREIGN KEY (fuente_principal_id) REFERENCES fuentes(id)
);

CREATE INDEX idx_procesos_organismo ON procesos(organismo_id);
CREATE INDEX idx_procesos_estado ON procesos(estado);
CREATE INDEX idx_procesos_oportunidad ON procesos(es_oportunidad);
CREATE INDEX idx_procesos_anio_convocatoria ON procesos(anio_convocatoria);
CREATE INDEX idx_procesos_fecha_cierre ON procesos(fecha_cierre);

CREATE TABLE publicaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_id BIGINT NOT NULL,
    fuente_id BIGINT NOT NULL,
    referencia TEXT,
    tipo TEXT NOT NULL,
    titulo TEXT,
    fecha_publicacion DATE,
    url TEXT NOT NULL,
    contenido_hash TEXT,
    contenido_texto TEXT,
    datos_json JSONB,
    detectada_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (proceso_id) REFERENCES procesos(id),
    FOREIGN KEY (fuente_id) REFERENCES fuentes(id)
);

CREATE INDEX idx_publicaciones_proceso ON publicaciones(proceso_id);
CREATE INDEX idx_publicaciones_fecha ON publicaciones(fecha_publicacion);
CREATE UNIQUE INDEX uq_publicaciones_fuente_ref_url
    ON publicaciones(fuente_id, referencia, url);

CREATE TABLE cambios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_id BIGINT NOT NULL,
    publicacion_id BIGINT,
    tipo TEXT NOT NULL,
    campo TEXT,
    valor_anterior TEXT,
    valor_nuevo TEXT,
    resumen TEXT NOT NULL,
    significativo BOOLEAN NOT NULL DEFAULT TRUE,
    detectado_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (proceso_id) REFERENCES procesos(id),
    FOREIGN KEY (publicacion_id) REFERENCES publicaciones(id)
);

CREATE INDEX idx_cambios_proceso ON cambios(proceso_id);
CREATE INDEX idx_cambios_significativo ON cambios(significativo);

-- user_id es el UUID de Supabase Auth; no se crea una tabla de usuarios local.
CREATE TABLE suscripciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    proceso_id BIGINT NOT NULL,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, proceso_id),
    FOREIGN KEY (proceso_id) REFERENCES procesos(id)
);

CREATE INDEX idx_suscripciones_user ON suscripciones(user_id, activa);
CREATE INDEX idx_suscripciones_proceso ON suscripciones(proceso_id, activa);

CREATE TABLE notificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suscripcion_id BIGINT NOT NULL,
    cambio_id BIGINT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'PENDIENTE',
    enviado_at TIMESTAMPTZ,
    error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(suscripcion_id, cambio_id),
    FOREIGN KEY (suscripcion_id) REFERENCES suscripciones(id),
    FOREIGN KEY (cambio_id) REFERENCES cambios(id)
);

CREATE INDEX idx_notificaciones_pendientes
    ON notificaciones(estado, created_at);
